### ISSUE TITLE
How does DNS work

### ISSUE THREAD

**Issue by samtay-dev** [Fakhruddin081/Task-#2]
#Please write your understanding of Domain Name Server.

- What happens in the background when we type www.google.com?

**Comment by Fakhruddin081** [comment]
Domain Name Service is like an address book for websites. 
When you type a web address in your browser,
 the browser looks at the DNS to find the website's IP address before it can retrieve the website.
 The browser needs to find out which server the website lives on,
 so that it can send HTTP messages to the right place.

when we type google.com and hit enter
 Your browser will try to resolve the hostname into an IP address. 
To do this, your computer makes a DNS request for “google.com”. 
This request is sent to the ip address of the domain servers configured on your computer

**Comment by Fakhruddin081** [comment]
Confirmed by @Fakhruddin081 that he understands
