### ISSUE TITLE
Question 5

### ISSUE THREAD

**Issue by samtay-dev** [Fakhruddin081/Task-#5]
# Loadbalancing

From a networking perspective, Can you tell me the difference between a Layer 4 Load Balancer vs. a Layer 7 Load Balancer?

**Comment by Fakhruddin081** [comment]
Load balancers are responsible for managing and distributing load to our backend systems.
A load balancer serves as the single point of contact for clients. The load balancer distributes incoming traffic across multiple targets . Load balancing lets you evenly distribute network traffic to prevent failure caused by overloading a particular resource

Layer 4 load balancing takes place at the transport layer of the OSI model, which is in charge of delivering messages regardless of their content.
Layer 7 load balancing works at the application layer of the OSI model, which is in charge of the message’s actual content. 
Application Load Balancers route network traffic in a more complex way, typically for TCP-based traffic such as HTTP or HTTPS
